# Generated by Django 4.2.4 on 2023-09-08 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='books_categ_name_edff05_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='booksImage')),
                ('available', models.CharField(choices=[('AVA', 'Available'), ('EQU', 'Equipment'), ('DGE', 'Damaged'), ('LOE', 'Lose'), ('REP', 'Replacement'), ('OTR', 'Other')], default='AVA', max_length=3)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='books.category')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_list', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ManyToManyField(related_name='book_writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['-created'], name='books_book_created_725357_idx'), models.Index(fields=['name'], name='books_book_name_fbe345_idx'), models.Index(fields=['-updated'], name='books_book_updated_7fb2ff_idx')],
            },
        ),
    ]
